(function() {var implementors = {};
implementors['log'] = ["impl&lt;'a, A, R&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='http://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='http://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A, Output=R&gt; + 'a&gt;","impl&lt;'a, A, R&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;A&gt; for <a class='struct' href='http://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html' title='alloc::boxed::Box'>Box</a>&lt;<a class='trait' href='http://doc.rust-lang.org/nightly/alloc/boxed/trait.FnBox.html' title='alloc::boxed::FnBox'>FnBox</a>&lt;A, Output=R&gt; + 'a + <a class='trait' href='http://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a>&gt;",];implementors['stats'] = ["impl&lt;A&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.tuple.html'>(A,)</a>&gt; for <a class='struct' href='stats/univariate/kde/kernel/struct.Gaussian.html' title='stats::univariate::kde::kernel::Gaussian'>Gaussian</a>","impl&lt;'a, A, K&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.FnOnce.html' title='core::ops::FnOnce'>FnOnce</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.tuple.html'>(A,)</a>&gt; for <a class='struct' href='stats/univariate/kde/struct.Kde.html' title='stats::univariate::kde::Kde'>Kde</a>&lt;'a, A, K&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
